import os
from lib import const

GRPC_HOSTNAME = os.getenv('PI_MEETING_GRPC_HOSTNAME', 'localhost')
GRPC_PORT = int(os.getenv('PI_MEETING_GRPC_PORT', 4000))
MAIN_TASK_INTERVAL_DURATION = int(os.getenv('PI_MEETING_MAIN_TASK_INTERVAL_DURATION_MS', 100))
FRAMERATE = int(os.getenv('PI_MEETING_FRAME_PER_SECOND', 20))
CAMERA_BUFFER_SIZE = int(os.getenv('PI_MEETING_CAMERA_BUFFER_SIZE_IN_KB', 5*1024))*const.KB

VIDEO_RESOLUTION = (1024, 768) # (width, height)

